version: "3.9"

services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_DB: ${PG_DATABASE}
    ports:
      - "5433:5432"
    volumes:
      - ./db:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      retries: 5
      start_period: 5s

  backend:
    build: ./mood-muncher-backend
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - db

  frontend:
    build: ./mood-muncher-frontend
    ports:
      - "4200:80"
    depends_on:
      - backend

volumes:
  db_data: